# Introduction to Python Matrices and Numpy

## 1. Basics of NumPy

In [11]:
# import numpy library
import numpy as np

In [12]:
# One-Dimensional Array(All elements must have same datatype)

# 1) array
a = np.array([1, 2, 3])

# 2) arange
b = np.arange(3) #not arrange
c = np.arange(1, 20, 5) # from 1 to 20, incremented by 5

# 3) linspace
d = np.linspace(0, 30, 6, dtype = int) # 6 evenly spaced values in the interval [0, 30]

print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")
print(f"d: {d}")

a: [1 2 3]
b: [0 1 2]
c: [ 1  6 11 16]
d: [ 0  6 12 18 24 30]


In [36]:
# More Arrays

# ones: a new array filled with 1
ones = np.ones(5)

# zeros: a new array filled with 0
zeros = np.zeros(7, dtype = int)

# empty: a new array without initializing entries (trash values)
empty = np.empty(3)

# random: a new array with random numbers between [0, 1]
random = np.random.rand(7)

print(f"ones: {ones}")
print(f"zeors: {zeros}")
print(f"empty: {empty}")
print(f"random: {random}")

ones: [1. 1. 1. 1. 1.]
zeors: [0 0 0 0 0 0 0]
empty: [5.e-324 5.e-324 5.e-324]
random: [0.10778292 0.45523628 0.7517373  0.21254986 0.13467971 0.04336523
 0.87678217]


## 2. Multidimensional Arrays

In [41]:
# Create a Two-Dimensional Array
twoDimensionArr = np.array([[1, 3, 5], [7, 9 ,11]])

# reshape: One-Dimensional Array -> Multi-Dimensional Array
oneDim = np.array([1, 2, 3, 4, 5, 6])
multiDim = np.reshape(oneDim, (3, 2))

print(f"twoDimensionArr:\n {twoDimensionArr}\n")
print(f"oneDim\n: {oneDim}\n")
print(f"multiDim\n: {multiDim}")

twoDimensionArr:
 [[ 1  3  5]
 [ 7  9 11]]

oneDim
: [1 2 3 4 5 6]

multiDim
: [[1 2]
 [3 4]
 [5 6]]


In [50]:
# .ndim: dimensions of the array
print(f"Dimensions: {twoDimensionArr.ndim}")

# .shape: shape of the array - (rows, columns)
print(f"shape: {twoDimensionArr.shape}")

# .size: number of elements in the array
print(f"size: {twoDimensionArr.size}")

Dimensions: 2
shape: (2, 3)
size: 6


## 3. Array Math Operations

In [54]:
# Availabe for both 1-D and Multi-Dimensional Arrays
arr1 = np.array([1, 3, 5])
arr2 = np.array([2, 5, 8])

# +: Adding
print(arr1 + arr2)

# -: Subtracting
print(arr1 - arr2)

# *: Multiplying
print(arr1 * arr2)

[ 3  8 13]
[-1 -2 -3]
[ 2 15 40]


In [58]:
# Multiplying Vectors with a Scalar (Broadcasting)
# Boradcasting allows to perform operations on arrays of different shapes

vector = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
print(f"vector:\n {vector}\n")
print(f"vector * 3.14\n= {vector * 3.14}")


vector:
 [[1 3 5 7]
 [2 4 6 8]]

vector * 3.14
= [[ 3.14  9.42 15.7  21.98]
 [ 6.28 12.56 18.84 25.12]]


## 4. Indexing and Slicing

In [24]:
# Indexing

# 1-D
anArray = ([1, 2, 3, 4, 5, 6])
k = anArray[2] # third entry

# 2-D
Array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
l = Array2[2][1] # select 8

print(k)
print(l)

3
8


In [21]:
# slicing
# array[start: end: step]

oneDimArray = ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
slicedOneDimArray = oneDimArray[2:7:2]

# 2-D: [row, column]
twoDimArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
slicedTwoDimArray1 = twoDimArray[: ,1] # second column
slicedTwoDimArray2 = twoDimArray[1] # second row
slicedTwoDimArray3 = twoDimArray[1:3, 1:3] # 2-4 row, 2-4 column

print(slicedOneDimArray)
print(slicedTwoDimArray1)
print(slicedTwoDimArray2)
print(slicedTwoDimArray3)


[3, 5, 7]
[ 2  5  8 11]
[4 5 6]
[[5 6]
 [8 9]]


## 5. Stacking

In [30]:
arr1 = np.array([[1, 1], [2, 2]])
arr2 = np.array([[3, 3], [4, 4]])

# vstack: Stack the arrays vertically
verticalStack = np.vstack((arr1, arr2)) # not np.vstack(arr1, arr2)

# hstack: Stack the arrays horizontally
horizontalStack = np.hstack((arr1, arr2)) # not np.hstack(arr1, arr2)

print(f"vertical stack:\n {verticalStack}\n")
print(f"horizontal stack:\n {horizontalStack}")

vertical stack:
 [[1 1]
 [2 2]
 [3 3]
 [4 4]]

horizontal stack:
 [[1 1 3 3]
 [2 2 4 4]]
